language: cpp
compiler: clang
os:
- linux
- windows
- macos
script:
- if [ "$TRAVIS_OS_NAME" == "windows" ]; then clang++ dansay.cpp -o dansay.exe; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then clang++ dansay.cpp -o dansay; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then clang++ dansay.cpp -o dansay; fi
branches:
  only:
  - main